version: '3'

services:

  node:
    build:
      context: ./
    image: lucasbryan/nodenginx
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    container_name: node
    networks:
      - nodechallengenet
    tty: true
    command: "node index.js"
    depends_on:
      - db
 
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodechallengenet

  nginx:
    build:
      context: ./nginx/
    image: lucasbryan/nginxnode
    container_name: nginx
    tty: true
    networks: 
      - nodechallengenet
    ports:
      - 8080:80


networks:
  nodechallengenet:
    driver: bridge

